//! The scenario ladder (plan §9.5) as command streams on the test level.
//!
//! Fixed patterns are plain scripts. Closed-loop scenarios (optimal strafes, perfect bhops, edgebug and
//! jumpbug timing, long-jump takeoff) are generated by running our own model and freezing the commands
//! it chose; both simulations then get the identical stream.

use movement::cmd::{Buttons, UserCmd};
use movement::instrument::TechniqueDetector;
use movement::{process_movement, tick_interval, ModeKind, MovementConfig, MovementMode, PlayerState, PrimitiveWorld, Vec3};

pub struct Scenario {
    pub id: String,
    pub mode: ModeKind,
    pub tickrate: u32,
    /// Teleport target (one unit above the floor, so the player settles onto it).
    pub origin: Vec3,
    pub yaw: f32,
    /// Zero-input commands the server runs after the teleport, before the recorded stream starts.
    pub settle: u32,
    pub cmds: Vec<UserCmd>,
    pub isolates: &'static str,
}

impl Scenario {
    pub fn dir_name(&self) -> String {
        format!("{}_{}_{}", self.id, crate::capture::mode_name(self.mode), self.tickrate)
    }
}

/// Generator: a running copy of our sim that records every command it is given.
pub struct Gen<'w> {
    world: &'w PrimitiveWorld,
    cfg: MovementConfig,
    mode: Box<dyn MovementMode + Send + Sync>,
    pub state: PlayerState,
    det: TechniqueDetector,
    dt: f32,
    pub rate: u32,
    pub pitch: f32,
    pub yaw: f32,
    pub cmds: Vec<UserCmd>,
    kind: ModeKind,
    origin: Vec3,
    yaw0: f32,
    settle: u32,
}

#[derive(Clone, Copy, PartialEq, Eq)]
pub enum Side {
    Left,
    Right,
}

impl<'w> Gen<'w> {
    fn new(world: &'w PrimitiveWorld, kind: ModeKind, rate: u32, origin: Vec3, yaw: f32, settle: u32) -> Self {
        let mode = kind.create();
        let cfg = *mode.config();
        let mut g = Gen {
            world,
            cfg,
            mode,
            state: PlayerState::new(origin),
            det: TechniqueDetector::default(),
            dt: tick_interval(rate),
            rate,
            pitch: 0.0,
            yaw,
            cmds: Vec::new(),
            kind,
            origin,
            yaw0: yaw,
            settle,
        };
        for _ in 0..settle {
            let c = UserCmd::from_buttons(0, Vec3::new(0.0, yaw, 0.0), Buttons::NONE);
            g.sim(&c);
        }
        g
    }

    fn sim(&mut self, cmd: &UserCmd) {
        process_movement(&self.cfg, self.mode.as_mut(), self.world, &mut self.state, cmd, &mut self.det, self.dt);
    }

    /// Ticks in `secs` seconds at this tickrate.
    pub fn t(&self, secs: f32) -> u32 {
        (secs * self.rate as f32).round() as u32
    }

    pub fn step(&mut self, b: Buttons) -> movement::TechniqueFlags {
        let mut c = UserCmd::from_buttons(self.cmds.len() as u32, Vec3::new(self.pitch, self.yaw, 0.0), b);
        c.tick = self.cmds.len() as u32;
        self.sim(&c);
        self.cmds.push(c);
        self.det.last
    }

    pub fn hold(&mut self, b: Buttons, ticks: u32) -> &mut Self {
        for _ in 0..ticks {
            self.step(b);
        }
        self
    }

    pub fn secs(&mut self, b: Buttons, secs: f32) -> &mut Self {
        let n = self.t(secs);
        self.hold(b, n)
    }

    pub fn turning(&mut self, b: Buttons, secs: f32, deg_per_sec: f32) -> &mut Self {
        for _ in 0..self.t(secs) {
            self.yaw += deg_per_sec / self.rate as f32;
            self.step(b);
        }
        self
    }

    /// Whether `b` this tick would leave the player airborne, without committing it.
    fn would_leave_ground(&self, b: Buttons) -> bool {
        let mut probe = self.fork();
        probe.step(b);
        !probe.state.on_ground()
    }

    /// An independent copy, rebuilt by replaying the recorded commands so mode-private state (KZ
    /// prestrafe) is exact too.
    fn fork(&self) -> Gen<'w> {
        let mut f = Gen::new(self.world, self.kind, self.rate, self.origin, self.yaw0, self.settle);
        for c in &self.cmds {
            f.sim(c);
        }
        f.cmds = self.cmds.clone();
        f.pitch = self.pitch;
        f.yaw = self.yaw;
        f
    }

    /// Hold `b` until the next tick would leave the ground, then jump on the last grounded tick.
    pub fn run_and_jump_at_edge(&mut self, b: Buttons, max_ticks: u32) -> &mut Self {
        for _ in 0..max_ticks {
            if self.state.on_ground() && self.would_leave_ground(b) {
                self.step(b | Buttons::JUMP);
                return self;
            }
            self.step(b);
        }
        self
    }

    /// Yaw that puts the strafe wish direction at the max-gain angle to the velocity [Ref §6].
    fn optimal_yaw(&self, side: Side) -> f32 {
        let v = self.state.velocity;
        let speed = v.length_2d();
        if speed < 1.0 {
            return self.yaw;
        }
        let accel = self.cfg.air_accelerate * self.cfg.weapon_max_speed * self.dt * self.state.surface_friction;
        let cos = ((self.cfg.air_wish_cap - accel) / speed).clamp(-1.0, 1.0);
        let theta = cos.acos().to_degrees();
        let vel_yaw = v.y.atan2(v.x).to_degrees();
        match side {
            // D: wish = right vector (yaw - 90); turn clockwise.
            Side::Right => vel_yaw - theta + 90.0,
            // A: wish = -right (yaw + 90); turn counter-clockwise.
            Side::Left => vel_yaw + theta - 90.0,
        }
    }

    pub fn strafe(&mut self, side: Side, ticks: u32, extra: Buttons) -> &mut Self {
        let key = if side == Side::Right { Buttons::RIGHT } else { Buttons::LEFT };
        for _ in 0..ticks {
            if self.state.on_ground() && !self.cmds.is_empty() {
                break;
            }
            self.yaw = wrap(self.optimal_yaw(side));
            self.step(key | extra);
        }
        self
    }

    /// Alternate optimal strafes every `half` ticks until the player lands.
    pub fn sync_until_land(&mut self, half: u32, max_ticks: u32) -> &mut Self {
        let mut side = Side::Left;
        let mut n = 0;
        while n < max_ticks {
            for _ in 0..half {
                if self.state.on_ground() {
                    return self;
                }
                self.strafe(side, 1, Buttons::NONE);
                n += 1;
            }
            side = if side == Side::Left { Side::Right } else { Side::Left };
        }
        self
    }

    fn try_variant(&self, f: impl FnOnce(&mut Gen<'w>) -> movement::TechniqueFlags) -> movement::TechniqueFlags {
        let mut probe = self.fork();
        f(&mut probe)
    }
}

fn wrap(mut y: f32) -> f32 {
    while y > 180.0 {
        y -= 360.0;
    }
    while y <= -180.0 {
        y += 360.0;
    }
    y
}

const W: Buttons = Buttons::FORWARD;
const J: Buttons = Buttons::JUMP;
const C: Buttons = Buttons::DUCK;
const NONE: Buttons = Buttons::NONE;

fn above(x: f32, y: f32, z: f32) -> Vec3 {
    Vec3::new(x, y, z + 1.0)
}

struct Builder<'w> {
    world: &'w PrimitiveWorld,
    out: Vec<Scenario>,
}

impl<'w> Builder<'w> {
    #[allow(clippy::too_many_arguments)]
    fn add(
        &mut self,
        id: &str,
        modes: &[ModeKind],
        isolates: &'static str,
        origin: Vec3,
        yaw: f32,
        settle_secs: f32,
        script: impl Fn(&mut Gen<'w>) -> bool,
    ) {
        for &mode in modes {
            for rate in [64u32, 128] {
                if mode == ModeKind::SimpleKz && rate != 128 {
                    continue;
                }
                let settle = ((settle_secs * rate as f32).round() as u32).max(1);
                let mut g = Gen::new(self.world, mode, rate, origin, yaw, settle);
                if !script(&mut g) {
                    eprintln!("warning: scenario {id} ({mode:?} {rate}) did not reach its target in our model; skipped");
                    continue;
                }
                self.out.push(Scenario {
                    id: id.to_string(),
                    mode,
                    tickrate: rate,
                    origin,
                    yaw,
                    settle,
                    cmds: std::mem::take(&mut g.cmds),
                    isolates,
                });
            }
        }
    }
}

pub fn all(world: &PrimitiveWorld) -> Vec<Scenario> {
    let v = [ModeKind::Vanilla];
    let all_modes = [ModeKind::Vanilla, ModeKind::KzTimer, ModeKind::SimpleKz];
    let mut b = Builder { world, out: Vec::new() };
    let (fx, fy) = testlevel::FAR;
    let settle = 0.5;

    // Ground (S0-S3).
    b.add("S0", &v, "settling, ground snap", above(0.0, 0.0, 0.0), 0.0, settle, |g| {
        g.hold(NONE, 100);
        true
    });
    for (id, x, y) in [("S1", 0.0, 0.0), ("S1F", fx, fy)] {
        b.add(id, &v, "ground accel, friction, stop speed", above(x, y, 0.0), 0.0, settle, |g| {
            g.secs(W, 1.0).secs(NONE, 1.0);
            true
        });
    }
    b.add("S2", &v, "counter-strafe", above(0.0, 0.0, 0.0), 0.0, settle, |g| {
        g.secs(W, 1.0).secs(Buttons::BACK, 0.1).secs(NONE, 0.5);
        true
    });
    b.add("S2b", &v, "side counter-strafe", above(0.0, 0.0, 0.0), 0.0, settle, |g| {
        g.secs(Buttons::RIGHT, 1.0).secs(Buttons::LEFT, 0.1).secs(NONE, 0.5);
        true
    });
    b.add("S3", &v, "walk multiplier", above(0.0, 0.0, 0.0), 0.0, settle, |g| {
        g.secs(W | Buttons::WALK, 1.0).secs(NONE, 0.5);
        true
    });
    b.add("S3c", &v, "crouch-walk", above(0.0, 0.0, 0.0), 0.0, settle, |g| {
        g.secs(C, 0.3).secs(W | C, 1.0).secs(C, 0.3).secs(NONE, 0.5);
        true
    });

    // Air (S4-S9).
    for (id, x, y) in [("S4", 0.0, 0.0), ("S4F", fx, fy)] {
        b.add(id, &all_modes, "jump, split gravity, stamina", above(x, y, 0.0), 0.0, settle, |g| {
            g.hold(J, 1).secs(NONE, 1.2);
            true
        });
    }
    b.add("S5", &all_modes, "air accel, deadstrafe window", above(0.0, 0.0, 0.0), 0.0, settle, |g| {
        g.secs(W, 0.5).hold(W | J, 1).turning(Buttons::RIGHT, 0.7, -150.0).secs(NONE, 0.5);
        true
    });
    b.add("S6", &v, "max-gain strafing", above(0.0, 0.0, 0.0), 0.0, settle, |g| {
        g.secs(W, 0.5).hold(W | J, 1);
        let n = g.t(1.5);
        g.strafe(Side::Right, n, NONE).secs(NONE, 0.3);
        true
    });
    // Bhop chains travel about 2000 units: start where the run is clear (the far pad is 2048 wide).
    for (id, x, y) in [("S7", 0.0, -1000.0), ("S7F", fx - 950.0, fy)] {
        b.add(id, &all_modes, "perfect bhops, anti-bhop cap, stamina", above(x, y, 0.0), 0.0, settle, |g| {
            g.secs(W, 1.0);
            let mut jumps = 0;
            let mut guard = 0;
            while jumps < 10 && guard < g.t(12.0) {
                guard += 1;
                if g.state.on_ground() {
                    g.step(W | J);
                    jumps += 1;
                } else {
                    g.step(W);
                }
            }
            g.secs(NONE, 0.5);
            jumps == 10
        });
    }
    b.add("S8", &v, "late bhop friction", above(0.0, -1000.0, 0.0), 0.0, settle, |g| {
        g.secs(W, 1.0).hold(W | J, 1);
        let mut hops = 0;
        let mut grounded = 0;
        let mut guard = 0;
        while hops < 3 && guard < g.t(6.0) {
            guard += 1;
            if g.state.on_ground() {
                grounded += 1;
                if grounded == 2 {
                    g.step(W | J);
                    hops += 1;
                    grounded = 0;
                    continue;
                }
            }
            g.step(W);
        }
        g.secs(NONE, 0.5);
        hops == 3
    });
    for (i, h) in [128.0, 256.0, 512.0].into_iter().enumerate() {
        let x = 3200.0 + 400.0 * i as f32 + 80.0;
        b.add(&format!("S9-{h}"), &v, "fall, landing stamina, check_falling", above(x, 1480.0, h), 0.0, settle, |g| {
            g.secs(W, 0.6).secs(NONE, 2.5);
            true
        });
    }

    // Collision (S10-S13).
    for yaw in [180.0, 150.0, 120.0] {
        b.add(&format!("S10-{yaw}"), &v, "wall plane clipping", above(-1400.0, 0.0, 0.0), yaw, settle, |g| {
            g.secs(W, 1.5).secs(NONE, 0.3);
            true
        });
    }
    for yaw in [134.0, 120.0] {
        b.add(&format!("S11-{yaw}"), &v, "two-plane crease", above(-1400.0, 850.0, 0.0), yaw, settle, |g| {
            g.secs(W, 1.5).secs(NONE, 0.3);
            true
        });
    }
    b.add("S12-18up", &v, "step_move 18", above(150.0, -2320.0, 0.0), 0.0, settle, |g| {
        g.secs(W, 2.0).secs(NONE, 0.3);
        true
    });
    b.add("S12-16up", &v, "step_move 16", above(150.0, -2620.0, 0.0), 0.0, settle, |g| {
        g.secs(W, 2.0).secs(NONE, 0.3);
        true
    });
    b.add("S12-19", &v, "19 unit riser blocks", above(150.0, -2920.0, 0.0), 0.0, settle, |g| {
        g.secs(W, 1.0).secs(NONE, 0.3);
        true
    });
    b.add("S12-18down", &v, "walking down stairs, stay_on_ground", above(700.0, -2320.0, 144.0), 180.0, settle, |g| {
        g.secs(W, 2.0).secs(NONE, 0.3);
        true
    });
    for (i, (angle, rise)) in testlevel::RAMPS.into_iter().enumerate() {
        if angle >= 70.0 {
            continue;
        }
        let y = -1400.0 + 400.0 * i as f32 + 128.0;
        let a = angle as u32;
        b.add(&format!("S13-{a}-walk"), &v, "walkable threshold, ramp walk", above(-3800.0, y, 0.0), 0.0, settle, |g| {
            g.secs(W, 2.5).secs(NONE, 0.3);
            true
        });
        b.add(&format!("S13-{a}-jump"), &v, "jump onto ramp", above(-3800.0, y, 0.0), 0.0, settle, |g| {
            g.secs(W, 0.6).hold(W | J, 1).secs(W, 1.5).secs(NONE, 0.3);
            true
        });
        // Dropped onto the slope from just above it: no settle, the recorded stream starts mid-air.
        let z = 66.0 * rise / 256.0 + 20.0;
        b.add(&format!("S13-{a}-slide"), &v, "slide / ground classification", Vec3::new(-3550.0, y, z), 0.0, 0.0, |g| {
            g.secs(NONE, 1.5);
            true
        });
    }

    // Duck and ledges (S14, S15).
    for (i, h) in [54.0, 55.0, 56.0, 57.0, 58.0].into_iter().enumerate() {
        let x = 300.0 + 256.0 * (i + 1) as f32 - 40.0;
        let o = above(x, -1500.0, 0.0);
        let hh = h as u32;
        b.add(&format!("S14-{hh}-std"), &v, "standing jump height", o, 0.0, settle, |g| {
            g.hold(W | J, 1).secs(W, 1.0);
            true
        });
        b.add(&format!("S14-{hh}-cj"), &v, "crouch jump (duck after jump)", o, 0.0, settle, |g| {
            g.hold(W | J, 1).secs(W | C, 0.8).secs(W, 0.3);
            true
        });
        b.add(&format!("S14-{hh}-jd"), &v, "jump and duck same tick", o, 0.0, settle, |g| {
            g.hold(W | J | C, 1).secs(W | C, 0.8).secs(W, 0.3);
            true
        });
        b.add(&format!("S14-{hh}-dj"), &v, "begin-duck jump", o, 0.0, settle, |g| {
            g.hold(W | C, 1).hold(W | J | C, 1).secs(W | C, 0.8).secs(W, 0.3);
            true
        });
    }
    b.add("S15-ground", &v, "duck/unduck on ground", above(0.0, 0.0, 0.0), 0.0, settle, |g| {
        g.secs(C, 0.5).secs(NONE, 0.5);
        true
    });
    b.add("S15-spam", &v, "duck speed penalty", above(0.0, 0.0, 0.0), 0.0, settle, |g| {
        for _ in 0..g.t(1.0) / 4 {
            g.hold(C, 2).hold(NONE, 2);
        }
        g.secs(NONE, 0.5);
        true
    });
    // Slow unduck at the 1.5 floor (hull-return threshold), then presses at rising fatigue levels
    // (refusal threshold).
    b.add("S15-slow", &v, "unduck hull threshold, fatigue refusal", above(0.0, 0.0, 0.0), 0.0, settle, |g| {
        g.secs(C, 0.4).secs(NONE, 0.3).secs(C, 0.8).secs(NONE, 1.0);
        for wait in [0.2, 0.15, 0.15, 0.15, 0.15] {
            g.secs(C, 0.2).secs(NONE, wait);
        }
        g.secs(NONE, 0.5);
        true
    });
    b.add("S15-air", &v, "airborne duck/unduck hull shift", above(0.0, 0.0, 0.0), 0.0, settle, |g| {
        g.hold(J, 1).hold(NONE, 5).secs(C, 0.3).secs(NONE, 0.6);
        true
    });
    b.add("S15-ceiling", &v, "can_unduck under a low ceiling", above(550.0, -800.0, 0.0), 0.0, settle, |g| {
        g.secs(C, 0.3).secs(W | C, 3.5).secs(W, 3.5).secs(NONE, 0.3);
        true
    });

    // Techniques (S16-S18), found by searching our model, then frozen.
    b.add("S16-edgebug", &v, "edgebug ordering", above(2200.0, -2450.0, 800.0), 0.0, settle, |g| edgebug(g));
    for (h, x) in [(128.0, 3340.0), (256.0, 3740.0)] {
        let hh = h as u32;
        b.add(&format!("S17-jumpbug-{hh}"), &v, "jumpbug", above(x, 1480.0, h), 0.0, settle, |g| drop_bug(g, true));
        b.add(&format!("S17-duckbug-{hh}"), &v, "duckbug", above(x, 1480.0, h), 0.0, settle, |g| drop_bug(g, false));
    }
    for (tag, up, down) in [("a", -45.0, 45.0), ("b", -20.0, 30.0)] {
        b.add(&format!("S18-{tag}"), &v, "ladder attach, climb, detach", above(-1000.0, 2480.0, 0.0), 0.0, settle, move |g| {
            let mut n = 0;
            while g.state.move_type != movement::MoveType::Ladder && n < g.t(2.0) {
                g.step(W);
                n += 1;
            }
            if g.state.move_type != movement::MoveType::Ladder {
                return false;
            }
            g.pitch = up;
            g.secs(W, 1.0);
            g.pitch = down;
            g.secs(W, 0.3);
            g.pitch = 0.0;
            g.secs(NONE, 0.3).hold(J, 1).secs(NONE, 0.8);
            true
        });
    }

    // Long jumps (S19) on the runway rows.
    for row in [1u32, 2, 3] {
        let gap = 220 + 10 * row;
        let y = -512.0 + 128.0 * row as f32 + 64.0;
        b.add(&format!("S19-{gap}"), &all_modes, "long jump distance", above(1564.0, y, 64.0), 0.0, settle, |g| {
            g.run_and_jump_at_edge(W, g.t(6.0));
            let half = g.t(0.25);
            let max = g.t(2.0);
            g.sync_until_land(half, max).secs(NONE, 0.3);
            true
        });
    }
    // Prestrafe (S20): turning while running forward-sideways, then a jump, so the KZ prestrafe
    // multipliers [Ref §20] are exercised; vanilla shows there is none.
    for (tag, rate_deg) in [("a", 90.0), ("b", 140.0)] {
        b.add(&format!("S20-{tag}"), &all_modes, "prestrafe while turning", above(0.0, 0.0, 0.0), 0.0, settle, move |g| {
            g.secs(W, 0.4).turning(W | Buttons::LEFT, 1.2, rate_deg).hold(W | J, 1).secs(NONE, 1.0);
            true
        });
    }
    b.out
}

/// Run off the tower and jump at its edge toward the platform's far edge, scanning the run yaw until
/// our model produces an edgebug there [Ref §14].
fn edgebug(g: &mut Gen) -> bool {
    for i in 0..1200 {
        let mut p = g.fork();
        p.yaw = i as f32 * 0.025;
        let n = p.t(3.0);
        p.run_and_jump_at_edge(W, n);
        for _ in 0..p.t(2.5) {
            let f = p.step(NONE);
            if f.edgebug {
                p.secs(NONE, 0.5);
                *g = p;
                return true;
            }
            if p.state.on_ground() {
                break;
            }
        }
    }
    false
}

/// Leave the tower, duck in the air, then release duck (and press jump for a jumpbug) on the command
/// where our model reports the technique [Ref §15]. Leaving the edge is tick-quantized, so the fall
/// phase is varied by jumping off or not and by when the airborne duck (a 9-unit hull shift) happens.
fn drop_bug(g: &mut Gen, jump: bool) -> bool {
    let release = if jump { J } else { NONE };
    // Ducked before leaving the edge, scanning yaw (finds the 128-tick cases).
    for i in 0..160 {
        let mut p = g.fork();
        p.yaw = i as f32 * 0.25;
        for _ in 0..p.t(2.0) {
            if !p.state.on_ground() {
                break;
            }
            p.step(W | C);
        }
        for _ in 0..p.t(3.0) {
            let flags = p.try_variant(|q| q.step(release));
            if (jump && flags.jumpbug) || (!jump && flags.duckbug) {
                p.step(release);
                p.secs(NONE, 0.5);
                *g = p;
                return true;
            }
            if p.state.on_ground() {
                break;
            }
            p.step(C);
        }
    }
    for jump_off in [false, true] {
        for duck_at in 0..g.t(0.6) {
            let mut p = g.fork();
            if jump_off {
                let n = p.t(2.0);
                p.run_and_jump_at_edge(W, n);
            } else {
                for _ in 0..p.t(2.0) {
                    if !p.state.on_ground() {
                        break;
                    }
                    p.step(W);
                }
            }
            for _ in 0..duck_at {
                p.step(NONE);
            }
            for _ in 0..p.t(3.0) {
                if p.state.on_ground() {
                    break;
                }
                if p.state.ducked {
                    let flags = p.try_variant(|q| q.step(release));
                    if (jump && flags.jumpbug) || (!jump && flags.duckbug) {
                        p.step(release);
                        p.secs(NONE, 0.5);
                        *g = p;
                        return true;
                    }
                }
                p.step(C);
            }
        }
    }
    false
}

